/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    fontSize: {
      'xs': ['0.75rem'],
      'md': ['1rem'],
      'lg': ['1.125rem'],
      'xl': ['1.25rem'],
      '2xl': ['1.5rem'],
      '3xl': ['1.875rem'],
      '4xl': ['2.25rem'],
      '5xl': ['3rem'],
    },
    colors: {
      "default-bg-d": "#262935",
      "default-bg": "#FFFFFF",
      "content-bg-d": "#181921",
      "content-bg": "#f8f8f2",
      "default-fg-d": "#f8f8f2",
      "default-fg": "#272A36",
      "pink-d": "#ff79c6",
      "pink": "#9E156E",
      "purple-d": "#bd93f9",
      "purple": "#64419E",
      "orange-d": "#ffb86c",
      "orange": "#b55e00",
      "cyan-d": "#8be9fd",
      "cyan": "#005D6F",
      "green-d": "#50fa7b",
      "green": "#016201",
      "yellow-d": "#f1fa8c",
      "yellow": "#4C5B00",
      "red-d": "#ff5555",
      "red": "#AC001C",
    },
    extend: {},
  },
  plugins: [],
}
