import Head from 'next/head'
import styles from "styles/Layout.module.scss";
import className from "utils/className";
import Header from "components/Header";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.page}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundColor="#f4f5f6"
      >
        <div className={className(styles.maxWidthWrapper)}>
          <Header />
        </div>
      </Box>
      <div className={className(styles.maxWidthWrapper)}>
      </div>
    </div>
  )
}
